FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app/src

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    libpq-dev \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

RUN pip install uv

COPY ../src ./src
COPY ../pyproject.toml ../uv.lock ./
COPY ../alembic.ini ./
COPY ../migrations ./migrations

RUN uv sync --frozen --dev

COPY docker/entrypoint-worker.sh /app/entrypoint-worker.sh
RUN chmod +x /app/entrypoint-worker.sh

ENTRYPOINT ["/app/entrypoint-worker.sh"]
